### ISSUE TITLE
Some terms does not have color highlighting.

### ISSUE THREAD

**Issue by sheeeng** [malmaud/vscode_tmux#2]
Some terms, mentioned in the [documentation](https://manpages.ubuntu.com/manpages/focal/man1/tmux.1.html), does not have color highlighting.

For example, `run-shell`, ` visual-activity`, `status-style`, and `unbind-key` terms does not have color highlighting.

**Comment by edouard-lopez** [comment]
Look like it's something to add in:
 
https://github.com/malmaud/vscode_tmux/blob/7956b6db8eed960a51eab8b9209ed73a837261e3/syntaxes/tmux.tmLanguage.json#L38

**Comment by malmaud** [comment]
I added some more keywords and constants. Let me know if there are still issues.
