### ISSUE TITLE
Match “tmux.conf” even without a leading dot

### ISSUE THREAD

**Issue by FranklinYu** [malmaud/vscode_tmux#3]
Vim by default recognizes `tmux.conf` as tmux configuration:

https://github.com/vim/vim/blob/c689f8c3d98fffe7e13730e198ce120934528f9c/runtime/filetype.vim#L1887-L1888

Not sure whether it’s possible in VS Code.

**Comment by malmaud** [comment]
Great idea, it looks like it is possible and I pushed the change.
