### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by cevhyruz** [malmaud/vscode_tmux#4]
Tmux is constantly pushing breaking changes, especially for syntax, is this project still active?

**Comment by edouard-lopez** [comment]
@cevhyruz Several options here:
1. You can [submit a tiny PR](https://github.com/malmaud/vscode_tmux/pull/6) :heavy_check_mark:  and ping @malmaud for review/merge, wait a few weeks and decide
2. Fork and post a message on to communicate here to onboard contributors.

**Comment by malmaud** [comment]
Hey all, yes, I'm still active and will keep reviewing PRs. I'm not necessarily always keeping tabs on the newest tmux syntax myself and proactively updating this, though, so I appreciate the help.
